server: 
  port: 8082
spring:
  data:
    mongodb:
      host: ds137340.mlab.com
      port: 37340
      database: userr
      username: dongpt
      password: dongpt
  application:
    name: dong